ClothingStore/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClothingStore.DataAccess;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace ClothingStore.Controllers
{
    public class ProductDetailsController : Controller
    {
        private readonly ClothingShopContext _context;

        public ProductDetailsController(ClothingShopContext context)
        {
            _context = context;
        }

        // GET: ProductDetails
        public async Task<IActionResult> Index()
        {
              return _context.ProductDetails != null ? 
                          View(await _context.ProductDetails.ToListAsync()) :
                          Problem("Entity set 'ClothingShopContext.ProductDetails'  is null.");
        }

        // GET: ProductDetails
        public async Task<IActionResult> Catalogue()
        {
            if (HttpContext.Session.GetString("cart") != null)
            {
                List<Cart> cart = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
                Console.WriteLine(HttpContext.Session.GetString("cart"));
                Console.WriteLine("Cart count====>" + cart[0].count);
            }
            return _context.ProductDetails != null ?
                        View(await _context.ProductDetails.ToListAsync()) :
                        Problem("Entity set 'ClothingShopContext.ProductDetails'  is null.");
        }

        // GET: ProductDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductDetails == null)
            {
                return NotFound();
            }

            var productDetail = await _context.ProductDetails
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (productDetail == null)
            {
                return NotFound();
            }

            return View(productDetail);
        }

        

        public async Task<IActionResult> Cart()
        {
            if(HttpContext.Session.GetString("cart") == null)
            {
                List<ProductDetail> productsList = new List<ProductDetail>();
                return View(productsList);
            } else
            {
                List<ProductDetail> productsList = new List<ProductDetail>();
                List<Cart> cart = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
                foreach (Cart cartItem in cart)
                {
                    var product = await _context.ProductDetails
                .FirstOrDefaultAsync(m => m.ProductId == cartItem.Id);
                    product.Count = cartItem.count;
                    productsList.Add(product);
                }
                return View(productsList);

            }
            
            Console.WriteLine("Name ========> ");
            return View();
        }

        public async Task<IActionResult> Checkout()
        {
            if (HttpContext.Session.GetString("loginId") == null)
            {
                
            }
            return RedirectToAction(nameof(Catalogue));
        }



        // GET: ProductDetails/Details/5
        public async Task<IActionResult> Product(int? id)
        {
            if (id == null || _context.ProductDetails == null)
            {
                return NotFound();
            }

            var productDetail = await _context.ProductDetails
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (productDetail == null)
            {
                return NotFound();
            }
            if (HttpContext.Session.GetString("cart") != null)
            {
                List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));

                foreach (Cart cItem in cartList)
                {
                    if (cItem.Id == productDetail.ProductId)
                    {

                        productDetail.Count = cItem.count;
                    }
                }
            }
                return View(productDetail);
        }

        // GET: ProductDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductType,ProductDescription,Price")] ProductDetail productDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem([Bind("ProductId,Count")] ProductDetail productDetail)
        {
            Console.WriteLine("id ======>" + productDetail.ProductId);
            Console.WriteLine("Count ======> " + productDetail.Count);
            if (HttpContext.Session.GetString("cart") == null)
            {

                List<Cart> cartList = new List<Cart>();
                Cart c = new Cart();
                c.Id = productDetail.ProductId;
                c.count = productDetail.Count;
                if (productDetail.Count > 0) { 
                cartList.Add(c); }

                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartList));
            }
            else
            {
                List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
                Cart c = new Cart();
                int flag = 0;
                foreach(Cart cItem in cartList)
                {
                    if(cItem.Id == productDetail.ProductId)
                    {
                        flag = 1;
                        cItem.count = productDetail.Count;
                    }
                }
                if(flag == 0)
                {
                    c.Id = productDetail.ProductId;
                    c.count = productDetail.Count;
                    cartList.Add(c);
                }
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartList));
            }
            return RedirectToAction(nameof(Catalogue));
        }

        //public string DictionaryToString(Dictionary<string, string> dictionary)
        //{
        //    string dictionaryString = "{";
        //    foreach (KeyValuePair<string, string> keyValues in dictionary)
        //    {
        //        dictionaryString += keyValues.Key + " : " + keyValues.Value + ", ";
        //    }
        //    return dictionaryString.TrimEnd(',', ' ') + "}";
        //}
        // GET: ProductDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProductDetails == null)
            {
                return NotFound();
            }

            var productDetail = await _context.ProductDetails.FindAsync(id);
            if (productDetail == null)
            {
                return NotFound();
            }
            return View(productDetail);
        }



        // POST: ProductDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ProductType,ProductDescription,Price")] ProductDetail productDetail)
        {
            if (id != productDetail.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductDetailExists(productDetail.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productDetail);
        }

        // GET: ProductDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProductDetails == null)
            {
                return NotFound();
            }

            var productDetail = await _context.ProductDetails
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (productDetail == null)
            {
                return NotFound();
            }

            return View(productDetail);
        }

        // POST: ProductDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProductDetails == null)
            {
                return Problem("Entity set 'ClothingShopContext.ProductDetails'  is null.");
            }
            var productDetail = await _context.ProductDetails.FindAsync(id);
            if (productDetail != null)
            {
                _context.ProductDetails.Remove(productDetail);
            }
            
            await _context.SaveChangesAsync();

ClothingStore/Controllers/UserLoginsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClothingStore.DataAccess;

namespace ClothingStore.Controllers
{
    public class UserLoginsController : Controller
    {
        private readonly ClothingShopContext _context;

        public UserLoginsController(ClothingShopContext context)
        {
            _context = context;
        }

        // GET: UserLogins
        public async Task<IActionResult> Index()
        {
            var clothingShopContext = _context.UserLogins.Include(u => u.User);
            return View(await clothingShopContext.ToListAsync());
        }

        // GET: UserLogins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserLogins == null)
            {
                return NotFound();
            }

            var userLogin = await _context.UserLogins
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.CredentialId == id);
            if (userLogin == null)
            {
                return NotFound();
            }

            return View(userLogin);
        }

        // GET: UserLogins/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId");
            return View();
        }

        // POST: UserLogins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,Password")] UserLogin userLogin)
        {
            Console.WriteLine("yyyyyyyy======>  " + HttpContext.Session.GetString("signUpUserId"));
            int userId = int.Parse(HttpContext.Session.GetString("signUpUserId"));
            Console.WriteLine("ttttt======>  " + userId);
                //_context.Add(userLogin);
                //await _context.SaveChangesAsync();
                String sqlString = "Insert into UserLogin (UserId,UserName,Password) values ('" + userId + "','" + userLogin.UserName + "','" + userLogin.Password + "');";
                _context.Database.ExecuteSqlRaw(sqlString);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
            
        }

        // GET: UserLogins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserLogins == null)
            {
                return NotFound();
            }

            var userLogin = await _context.UserLogins.FindAsync(id);
            if (userLogin == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId", userLogin.UserId);
            return View(userLogin);
        }

        // POST: UserLogins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CredentialId,UserId,UserName,Password")] UserLogin userLogin)
        {
            if (id != userLogin.CredentialId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userLogin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserLoginExists(userLogin.CredentialId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.UserDetails, "UserId", "UserId", userLogin.UserId);
            return View(userLogin);
        }

        // GET: UserLogins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserLogins == null)
            {
                return NotFound();
            }

            var userLogin = await _context.UserLogins
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.CredentialId == id);
            if (userLogin == null)
            {
                return NotFound();
            }

            return View(userLogin);
        }

        // POST: UserLogins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserLogins == null)
            {
                return Problem("Entity set 'ClothingShopContext.UserLogins'  is null.");
            }
            var userLogin = await _context.UserLogins.FindAsync(id);
            if (userLogin != null)
            {
                _context.UserLogins.Remove(userLogin);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserLoginExists(int id)
        {
            return (_context.UserLogins?.Any(e => e.CredentialId == id)).GetValueOrDefault();
        }

        public async Task<ActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("UserName,Password")] UserLogin userLogin)
        {
            Console.WriteLine("un====>" + userLogin.UserName);
            Console.WriteLine("pass===>" + userLogin.Password);
            var users = await _context.UserLogins.ToListAsync();
            foreach (var user in users)
            {
                if(user.UserName == userLogin.UserName && user.Password == userLogin.Password)
                {
                    HttpContext.Session.SetString("loginId" , "" + user.UserId);

                    return RedirectToAction("Logged","UserDetails");
                }
            }
            return View();
        }

        public async Task<ActionResult> LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

ClothingStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClothingStore</title>
    @using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClothingStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
</head>
<body>
    <header>
       <!-- <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClothingStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>-->
                <nav>

            <div class="wrapper">
                <div class="left-box">
                   
                    <a class="nav-link" asp-area="" asp-controller="ProductDetails" asp-action="Cart"><img src="~/images/shopping_cart.png" alt="shopping cart"></a>
                </div>
                <div class="left-box">
                    @if(Accessor.HttpContext.Session.GetString("loginId") == null){
                        <form asp-controller="UserLogins" asp-action="Login">
                            <button type="submit"  class="btn" id="logButton">Login</button></form>

                    }else{
                        <form asp-controller="UserLogins" asp-action="LogOut">
                        <button type="submit" class="btn" id="logButton">Logout</button></form>
                    }

                </div>
                @if(Accessor.HttpContext.Session.GetString("loggedUserType") == "0")
                {
                     <form asp-controller="ProductDetails" asp-action="Index">
                            <button type="submit"  class="btn" id="inventory">Inventory</button></form>
                }

            </div>

            <div class="index">                
                <div class="drawer">
                    <div id="Logo">
                        <a href="index.html"><img  id='headerLogo' src="~/images/logo.png" alt="company logo"></a>
                    </div>
                </div>

                 <div class="menu">
                    <ul>
                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">HOME</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="ProductDetails" asp-action="Catalogue">PRODUCT</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">ABOUT</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a></li>
                    </ul>
                </div>
            </div>    
        </nav> 
    </header>
    <main>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </main>
     <footer>
        <div class="container4">
            <div class="row4-1">
                <a href="index.html" class="link_black"><img id='footerLogo' src="~/images/logo.png" alt="home" width="150px"></a>
                <p>123 Happy St., Ottawa, ON, Canada</p> 
                <p>(123) 456-7890</p>
                <p>mail@groupfive.ca</p>
            </div>  
            <div class="row4-2">
                <p><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">HOME</a></p>
                <p><a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">ABOUT</a></p>
                <p><a class="nav-link" asp-area="" asp-controller="ProductDetails" asp-action="Index">ONLINE SHOP</a></p>
                <p><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a></p>
            </div>
            <div class="row4-3">
                <h4>Order</h4>
                <p>Shopping cart</p>
                <p></p>

            </div>
            <div class="row4-4">
                <h4>Follow us</h4>
                <div class="sns">
                    <a href="https://www.facebook.com" target="_blank"><img src="~/images/Facebook.png" alt="Facebook"></a>
                    <a href="https://twitter.com" target="_blank"><img src="~/images/Twitter.png" alt="Twitter"></a>
                    <a href="https://www.instagram.com" target="_blank"><img src="~/images/Instagram.png" alt="Instagram"></a>
                </div>
            </div>
        </div>
        <div class="center">
            <p>© 2021 Group five</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>